<?php
    $router->get("/","HomeController@index");
    $router->get("/listing","HomeController@lisiting");
    $router->get("/listing/create","HomeController@create",["auth"]);
    $router->get("/listing/show/{id}","HomeController@show");
    $router->get("/listing/edit/{id}","HomeController@edit",["auth"]);
    $router->post("/listing/update/{id}","HomeController@update",["auth"]);
    $router->post("/listing","HomeController@store",["auth"]);
    $router->get("/listing/search","HomeController@search");
    $router->delete("/listing/{id}","HomeController@destroy",["auth"]);
    $router->get("/auth/register","UserController@create",["guest"]);
    $router->get("/auth/login","UserController@login",["guest"]);
    $router->post("/auth/login","UserController@login",["guest"]);
    $router->post("/auth/register","UserController@store",["guest"]);
    $router->post("/auth/logout","UserController@logout",["auth"]);
    $router->post("/auth/loginn","UserController@authenticate",["guest"]);
?>